//import './globals.css'
import './css/bootstrap.css'
import './css/style.css'
import './css/custom.css'
import './css/animate.css'
import { Inter } from 'next/font/google'
import Navbar from "@/app/components/common/navbar";
import Footer from "@/app/components/common/footer";
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'UCCL',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        {children}
      <Footer/>
      </body>
    </html>
  )
}
